version: "3.9"

services:
  postgres_db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: database
    networks:
      - dimatech

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head &&
                      python3.12 src/main.py"
    volumes:
      - os_data:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres_db
    container_name: main
    networks:
      - dimatech
  
volumes:
  postgres_data:
  os_data:
  static_volume:

networks:
  dimatech: